# SwiftLint Configuration for Velo

# Directories to exclude from linting
excluded:
  - Pods
  - DerivedData
  - .build
  - Packages

# Enabled rules
opt_in_rules:
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Too noisy
  # Note: line_length is configured below, not disabled

# Configure line length
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

# Configure file length
file_length:
  warning: 500
  error: 700

# Configure function length
function_body_length:
  warning: 50
  error: 100

# Configure type length
type_body_length:
  warning: 350
  error: 500

# Configure cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Force unwrapping
force_unwrapping:
  severity: warning

# Force cast
force_cast:
  severity: warning

# Nesting
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 8

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - x
    - y
    - i
    - j
    - to

# Type name
type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_hardcoded_api_keys:
    name: "No Hardcoded API Keys"
    regex: '(api_key|apiKey|API_KEY)\s*=\s*"[^"]{10,}"'
    message: "API keys should not be hardcoded. Use Secrets.swift or environment variables."
    severity: error

  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use Logger instead of print statements."
    severity: warning

  use_haptic_manager:
    name: "Use HapticManager"
    regex: 'UIImpactFeedbackGenerator|UINotificationFeedbackGenerator|UISelectionFeedbackGenerator'
    message: "Use HapticManager for haptic feedback."
    severity: warning

# Reporter type
reporter: "xcode"
